version: "3.3"
services:

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: boilerplate
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boilerplate"]
      interval: 5s
      timeout: 2s
      retries: 10

  db_test:
    image: postgres:12
    environment:
      POSTGRES_DB: boilerplate_test
      POSTGRES_USER: boilerplate_test
      POSTGRES_PASSWORD: boilerplate_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boilerplate_test"]
      interval: 5s
      timeout: 2s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@boilerplate.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "5050:80"
